### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MBoBr** [Stryzhh/DBDTimers#20]
Installed latest jre1.8.0_333 (and jdk as well), deleted old versions of java, cleared the register, set a correct PATH to a java's bin folder and the programm is still not launching, any clues? Windows 10.
 I tried different versions: the initial one launches but it lack settings (can't adjust timers etc etc), second version says that I have to install java environment and clolses, and the last two versions launch in the tray but nothing appears on the screen.

**Comment by MorGuux** [comment]
Hi there,

Try using the Java 11.0.15 JDK to run it. Java 11 uses custom JREs that are supplied with the respective software, but we never figured out how to compile a JRE for the app, hence the instruction to use the JDK. It was compiled with 11.0.15 though, so should run on there (you are trying to use Java 1.8 which is too old for that software).

**Comment by MBoBr** [comment]
Hi,
I completely uninstalled Java (both jre/jdk) and installed version you've mentioned (11.0.15 jdk) and everything work like a charm now! Thanks!

**Comment by MBoBr** [comment]
Also I didn't had to do all this PATH stuff.
